# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"

# baseURL = "https://thebenjam.in/"
languageCode = "en"
defaultContentLanguage = "en"


googleAnalytics = "G-F92NKPYC4B"

title = "Benjamin Anderson"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
enableRobotsTXT = true

images = ['img/avatar.png']

summaryLength = 0

[author]
  name = "Benjamin Anderson"
  image = "img/avatar.png"
  bio = "Disciple of Experience"
  links = [
     { email = "mailto:me@benjaminbanderson.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
     { instagram = "https://instagram.com/benjamin421" },
  #   { keybase = "https://keybase.io/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/benjamin-anderson-20707265" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/consciousrepo" },
  #   { youtube = "https://youtube.com/username" },
  ]
